### ISSUE TITLE
聲調跟母音一起處理

### ISSUE THREAD

**Issue by yenlp7964** [stanleyexp/uniquep#1]
#聲調跟母音一起處理
規則:a->o->e->i->u->ü
例子
馬聲 m-a3-sh-e1-ng
馬繩m-a3-sh-e2-ng
手套sh-o3-u-t-a4-o
保險套b-a3-o-x-i-a3-n-t-a3-o
保鮮膜 b-a3-o-x-i-a1-n-m-o2-u

**Comment by yenlp7964** [comment]
IPA聲母標音順序

**Comment by tingwei628** [comment]
[doc:中文IPA聲調標註規則](https://github.com/stanleyexp/uniquep/wiki/中文IPA聲調標註規則)

**Comment by tingwei628** [comment]
related https://github.com/stanleyexp/uniquep/issues/3#issuecomment-1067626439

close this issue
