### ISSUE TITLE
教育部辭典 to IPA+數字聲調

### ISSUE THREAD

**Issue by yenlp7964** [stanleyexp/uniquep#3]
漢語拚音+數字聲調/漢語拼音(教育部)/IPA無聲調/IPA+數字聲調
tsang1	cāng	tsʰɑŋ	tsʰɑŋ1
tsang2	cáng	tsʰɑŋ	tsʰɑŋ2
tsang3	cǎng	tsʰɑŋ	tsʰɑŋ3
tsang4	càng	tsʰɑŋ	tsʰɑŋ4
tsang5	cang 	tsʰɑŋ 	tsʰɑŋ

**Comment by tingwei628** [comment]
教育部 uniqueness point (無聲調) 已提交 [commit](959b95edc63750a0c5bc32f26b35a23297e7999b)

**Comment by tingwei628** [comment]
@yenlp7964
聲調符號(5) -> 聲調符號(無) 已提交 [commit](17a94e93a0e1ee425c08c138b6a21ddc7578ae2e)

**Comment by tingwei628** [comment]
close this issue
IPA to uniqueness point (tone) [commit](https://github.com/stanleyexp/uniquep/commit/f30bb7ed581df58c206fb2d42712c66f90c6f081)
